### ISSUE TITLE
Setting Custom Prior

### ISSUE THREAD

**Issue by jlevy44** [vdorie/stan4bart#5]
I see that bart_args allows us to specify dbarts control elements. How would one go about changing the tree prior (power, base)?

**Comment by vdorie** [comment]
Sorry for the delayed response; added in the most recent commit. `bart_args` now works with `power`, `base`, `split.probs`, and `k`. In order to work, requires a version of `dbarts` from [github](https://github.com/vdorie/dbarts).

**Comment by jlevy44** [comment]
Thank you!!
