### ISSUE TITLE
extract(model, type = "varcount") not working

### ISSUE THREAD

**Issue by bonStats** [vdorie/stan4bart#7]
I'm getting this error
`Error in extract.stan4bartFit(model, type = "varcount", combine_chains = F) : object 'result' not found`

I believe this line...
https://github.com/vdorie/stan4bart/blob/bfcb4c277f578cf3096e0cfc5075bf51c8a80ba6/R/generics.R#L280

should have "varcount" instead of "bart_varcount"

**Comment by vdorie** [comment]
Thanks! Fixed in 2e474c4.
